routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.index');
});

Auth::routes();

// Admin Routes
Route::middleware('auth')->name('portal.')->prefix('portal')->group(function () {
    Route::get('/', 'PortalController@index')->name('home');
    Route::prefix('admin')->name('admin.')->middleware('admin')->group( function(){
        Route::get('/', 'AdminController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('provider')->name('provider.')->group( function() {
            Route::get('/', 'AdminController@providers')->name('home');
            Route::get('create', 'AdminController@create')->name('create');
            Route::get('edit/{provider}', 'AdminController@edit')->name('edit');
            Route::post('store', 'AdminController@store')->name('store');
            Route::patch('update/{provider}', 'AdminController@update')->name('update');
            Route::get('delete/{provider}', 'AdminController@destroy')->name('delete');
        });
    });

    // Provider Routes
    Route::prefix('provider')->name('provider.')->middleware('provider')->group( function(){
        Route::get('/', 'ProviderController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('lecturer')->name('lecturer.')->group( function() {
            Route::get('/', 'ProviderController@lecturers')->name('home');
            Route::get('create', 'ProviderController@create')->name('create');
            Route::get('edit/{lecturer}', 'ProviderController@edit')->name('edit');
            Route::post('store', 'ProviderController@store')->name('store');
            Route::patch('update/{lecturer}', 'ProviderController@update')->name('update');
            Route::get('delete/{lecturer}', 'ProviderController@destroy')->name('delete');

            Route::get('activate/{lecturer}', 'ProviderController@activate')->name('activate');
            Route::get('deactivate/{lecturer}', 'ProviderController@deactivate')->name('deactivate');
        });
        Route::prefix('student')->name('student.')->group( function() {
            Route::get('/', 'ProviderController@students')->name('home');
            Route::get('edit/{student}', 'ProviderController@editStudent')->name('edit');
            Route::get('requests', 'ProviderController@studentRequests')->name('requests');
            Route::patch('update/{student}', 'ProviderController@updateStudent')->name('update');
            Route::get('delete/{student}', 'ProviderController@destroyStudent')->name('delete');

            Route::get('activate/{student}', 'ProviderController@activateStudent')->name('activate');
            Route::get('deactivate/{student}', 'ProviderController@deactivateStudent')->name('deactivate');
        });
    });

    // Student Routes
    Route::prefix('student')->name('student.')->middleware('student')->group( function() {
        Route::get('/', 'StudentController@index')->name('home');
        Route::get('/scans', 'StudentController@scans')->name('scans');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('assignment')->name('assignment.')->group( function() {
            Route::get('/', 'StudentController@assignments')->name('home');
            Route::get('/submission/{assignment}', 'StudentController@submission')->name('submission');
            Route::get('/submit/{assignment}', 'StudentController@submitAssignment')->name('submit');
            Route::post('/scan/{assignment}', 'StudentController@scanAssignment')->name('scan');
        });
    });
    // Instructor Routes
    Route::prefix('instructor')->name('instructor.')->middleware('instructor')->group( function() {
        Route::get('/', 'LecturerController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::get('/scans', 'LecturerController@scans')->name('scans');
        Route::prefix('assignment')->name('assignment.')->group( function() {
            Route::get('/', 'LecturerController@assignments')->name('home');
            Route::get('/create', 'LecturerController@createAssignment')->name('create');
            Route::get('/edit/{assignment}', 'LecturerController@createAssignment')->name('edit');
            Route::post('/store', 'LecturerController@storeAssignment')->name('store');
            Route::patch('/update/{assignment}', 'LecturerController@updateAssignment')->name('update');
            Route::get('/delete/{assignment}', 'LecturerController@destroyAssignment')->name('delete');
            Route::post('/scan/{assignment}', 'LecturerController@scanAssignment')->name('scan');
        });
        Route::prefix('course')->name('course.')->group( function() {
            Route::get('/', 'LecturerController@courses')->name('home');
            Route::get('/create', 'LecturerController@createCourse')->name('create');
            Route::post('/store', 'LecturerController@storeCourse')->name('store');
            Route::get('/edit/{course}', 'LecturerController@createCourse')->name('edit');
            Route::patch('/update/{course}', 'LecturerController@updateCourse')->name('update');
            Route::get('/delete/{course}', 'LecturerController@destroyCourse')->name('delete');
        });
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Lecturer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Lecturer extends Model
{
    use HasFactory;

    protected $primaryKey = 'user_id';
    protected $table = 'users';

    public function courses()
    {
        return $this->hasMany(Course::class, 'user_id');
    }
}

app/Http/Controllers/LecturerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Assignment;
use App\Models\Course;
use App\Models\Lecturer;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

class LecturerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('portal.lecturer.index');
    }

    public function courses()
    {
        $courses = Course::owner()->paginate(20);
        return view('portal.lecturer.courses', compact('courses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function createCourse(Course $course)
    {
        return view('portal.lecturer.create-course', ['course' => $course]);
    }
    public function storeCourse(Request $request)
    {
        $course = Course::whereCode($request->code)->first();
        if ($course){
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Duplicate Course Code.']);
        }
        $course_create = Course::create([
            'title' => $request->title,
            'code' => $request->code,
            'user_id' => \Auth::id(),
        ]);
        if ($course_create) {
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Course added successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }
    }
    public function updateCourse(Request $request, Course $course)
    {
        $update = $course->update([
            'title' => $request->title,
            'code' => $request->code,
            'user_id' => \Auth::id(),
        ]);
        if ($update) {
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Course updated successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function assignments()
    {
        $assignments = Assignment::whereUser_id(\Auth::id())->paginate(20);
        return view('portal.lecturer.assignments', compact('assignments'));
    }
    public function createAssignment(Assignment $assignment)
    {
        return view('portal.lecturer.create-assignment', compact('assignment'));
    }

    public function storeAssignment(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|string|min:3',
            'course' => 'required|string',
            'start_date' => 'required',
            'end_date' => 'required',
        ]);
        if ($validator->fails()){
            return redirect()->back()->withInput()->withErrors($validator->errors());
        }
        $input = $request->all();
        $input['user_id'] = \Auth::id();
        $input['status'] = '1';
        $input['start_date'] = Carbon::parse($request->start_date)->format('Y-m-d');
        $input['end_date'] = Carbon::parse($request->end_date)->format('Y-m-d');
        $save = Assignment::create($input);
        if ($save){
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Assignment created successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function show(Lecturer $lecturer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function edit(Lecturer $lecturer)
    {
        return view('portal.lecturer.create-assignment', compact('assignment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function updateAssignment(Request $request, Assignment $assignment)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|string|min:3',
            'course' => 'required|string',
            'start_date' => 'required',
            'end_date' => 'required',
        ]);
        if ($validator->fails()){
            return redirect()->back()->withInput()->withErrors($validator->errors());
        }
        $assignment->title = $request->title;
        $assignment->course = $request->course;
        $assignment->group_by = $request->group_by;
        $assignment->nwords = $request->nwords;
        $assignment->group_by = $request->group_by;
        $assignment->submit_before_end = $request->submit_before_end;
        $assignment->repo_source = $request->repo_source;
        $assignment->show_rel = $request->show_rel;
        $assignment->start_date = Carbon::parse($request->start_date)->format('Y-m-d');
        $assignment->end_date = Carbon::parse($request->end_date)->format('Y-m-d');

        if ($assignment->save()){
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Assignment updated successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lecturer $lecturer)
    {
        //
    }
    public function destroyAssignment(Assignment $assignment )
    {
        if ($assignment->delete()) {
            return Redirect::back()->with([ 'message' => "Assignment Deleted Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with([ 'message' => "Oops! Provider not deleted.", 'error' => true]);
        }
    }
    public function destroyCourse(Course $course )
    {
        if ($course->delete()) {
            return Redirect::back()->with([ 'message' => "Course Deleted Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with([ 'message' => "Oops! Provider not deleted.", 'error' => true]);
        }
    }
}

app/Http/Controllers/PortalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PortalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        dd(\Route::current()->getName() );
        $user = \Auth::user();
        $ul = $user->level;

        if ($ul == '3' ) {
            return redirect()->route('portal.admin.home');

        }  elseif ($ul == '2' ) {
            return redirect()->route('portal.provider.home');

        }   elseif ($ul == '1' ) {
            return redirect()->route('portal.instructor.home');

        }  else {
            # code...
            // if($request->ajax()){return response()->json(['ul'=> $ul], 200);}
            return redirect()->route('portal.student.home');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/portal/lecturer/assignments.blade.php
@extends('portal.lecturer.layout')
@section('title', 'Assignments')
@section('content')
<div class="intro-y flex items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        @yield('title')
    </h2>
</div>
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
        <a href="{{ route('portal.instructor.assignment.create') }}" class="btn btn-primary shadow-md mr-2">New Assignment</a>
        <div class="dropdown">
            <button class="dropdown-toggle btn px-2 box text-gray-700 dark:text-gray-300" aria-expanded="false">
                <span class="w-5 h-5 flex items-center justify-center"> <i class="w-4 h-4" data-feather="plus"></i> </span>
            </button>
            <div class="dropdown-menu w-40">
                <div class="dropdown-menu__content box dark:bg-dark-1 p-2">
                    <a href="" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md"> <i data-feather="printer" class="w-4 h-4 mr-2"></i> Print </a>
                    <a href="" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md"> <i data-feather="file-text" class="w-4 h-4 mr-2"></i> Export to Excel </a>
                    <a href="" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md"> <i data-feather="file-text" class="w-4 h-4 mr-2"></i> Export to PDF </a>
                </div>
            </div>
        </div>
        <div class="hidden md:block mx-auto text-gray-600">Showing 1 to 2 of 2 entries</div>
        <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            <div class="w-56 relative text-gray-700 dark:text-gray-300">
                <input type="text" class="form-control w-56 box pr-10 placeholder-theme-13" placeholder="Search scans by date range...">
                <i class="w-4 h-4 absolute my-auto inset-y-0 mr-3 right-0" data-feather="search"></i>
            </div>
        </div>
    </div>
    <!-- BEGIN: Data List -->
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        @include('portal.lecturer.inc.alert')
        @if (count($assignments) > 0)
        <table class="table table-report -mt-2">
            <thead>
            <tr>
                <th class="whitespace-nowrap">S/N</th>
                <th class="whitespace-nowrap">Title</th>
                <th class="text-center whitespace-nowrap">Status</th>
                <th class="text-center whitespace-nowrap">Due Date</th>
                <th class="text-center whitespace-nowrap">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($assignments as $assignment)
            <tr class="intro-x">
                <td>#{{ $assignment->id }}</td>
                <td class="w-60">
                    <a href="{{ route('portal.instructor.assignment.edit', $assignment->id) }}" class="font-medium whitespace-nowrap">{{ $assignment->title }}</a>
                    <!-- <div class="text-gray-600 text-xs whitespace-nowrap mt-0.5">Univerity of Port Harcourt</div> -->
                </td>
                <td class="w-40">
                    <div class="flex items-center justify-center @if($assignment->start_date->format('Y-m-d') <= today()->format('Y-m-d') && $assignment->end_date->format('Y-m-d') >= today()->format('Y-m-d') ) text-theme-9 @else text-theme-6 @endif">
                        @if($assignment->start_date->format('Y-m-d') <= today()->format('Y-m-d') && $assignment->end_date->format('Y-m-d') >= today()->format('Y-m-d') )  Ongoing @else Ended @endif
                    </div>
                </td>
                <td class="w-40">
                    <div class="flex items-center justify-center text-theme-6"> {{ $assignment->end_date->format('Y-m-d') }}</div>
                </td>
                <td class="table-report__action w-60">
                    <div class="flex justify-center sm:flex-row items-center">
                        <a class="flex items-center mr-3 text-theme-9" href="{{ route('portal.instructor.assignment.edit', $assignment->id) }}" > <i data-feather="eye" class="w-4 h-4 mr-1"></i> View </a>
                        <a class="flex items-center mr-3  text-theme-7" href="javascript:;"> <i data-feather="copy" class="w-4 h-4 mr-1"></i> Copy Link </a>
                        <a class="flex items-center  text-theme-6" href="{{ route('portal.instructor.assignment.delete', $assignment->id) }}"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </a>
                    </div>
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>
        @else
        @endif
    </div>
    <!-- END: Data List -->
    <!-- BEGIN: Pagination -->
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-nowrap items-center">
        <ul class="pagination">
          {!! $assignments->links() !!}
        </ul>
        <select class="w-20 form-select box mt-3 sm:mt-0">
            <option>10</option>
            <option>25</option>
            <option>35</option>
            <option>50</option>
        </select>
    </div>
    <!-- END: Pagination -->
</div>
<!-- BEGIN: Delete Confirmation Modal -->
<div id="delete-confirmation-modal" class="modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body p-0">
                <div class="p-5 text-center">
                    <i data-feather="x-circle" class="w-16 h-16 text-theme-6 mx-auto mt-3"></i>
                    <div class="text-3xl mt-5">Are you sure?</div>
                    <div class="text-gray-600 mt-2">
                        Do you really want to delete these records?
                        <br>
                        This process cannot be undone.
                    </div>
                </div>
                <div class="px-5 pb-8 text-center">
                    <button type="button" data-dismiss="modal" class="btn btn-outline-secondary w-24 mr-1">Cancel</button>
                    <button type="button" class="btn btn-danger w-24">Delete</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END: Delete Confirmation Modal -->
@endsection

resources/views/portal/lecturer/courses.blade.php
@extends('portal.lecturer.layout')
@section('title', 'Courses')
@section('content')
<div class="grid grid-cols-12 gap-6 mt-5">
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
        <a href="{{ route('portal.instructor.course.create') }}" class="btn btn-primary shadow-md mr-2">Add New Course</a>
        <div class="dropdown">
            <button class="dropdown-toggle btn px-2 box text-gray-700 dark:text-gray-300" aria-expanded="false">
                <span class="w-5 h-5 flex items-center justify-center"> <i class="w-4 h-4" data-feather="plus"></i> </span>
            </button>
            <div class="dropdown-menu w-40">
                <div class="dropdown-menu__content box dark:bg-dark-1 p-2">
                    <a href="" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md"> <i data-feather="printer" class="w-4 h-4 mr-2"></i> Print </a>
                    <a href="" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md"> <i data-feather="file-text" class="w-4 h-4 mr-2"></i> Export to Excel </a>
                    <a href="" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md"> <i data-feather="file-text" class="w-4 h-4 mr-2"></i> Export to PDF </a>
                </div>
            </div>
        </div>
        @if(count($courses) > 0) <div class="hidden md:block mx-auto text-gray-600">Showing 1 to 2 of 2 entries</div> @endif
        <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
            <div class="w-56 relative text-gray-700 dark:text-gray-300">
                <input type="text" class="form-control w-56 box pr-10 placeholder-theme-13 datepicker" placeholder="Search scans by date range...">
                <i class="w-4 h-4 absolute my-auto inset-y-0 mr-3 right-0" data-feather="search"></i>
            </div>
        </div>
    </div>
    <!-- BEGIN: Data List -->
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <table class="table table-report -mt-2">
            @if(count($courses) > 0)
            <thead>
                <tr>
                    <th class="whitespace-nowrap">Course Title</th>
                    <th class="whitespace-nowrap">Course Code</th>
                    <th class="text-center whitespace-nowrap">Created By</th>
                    <th class="text-center whitespace-nowrap">Date</th>
                    <th class="text-center whitespace-nowrap">Actions</th>
                </tr>
            </thead>
            @endif
            <tbody>
                @forelse($courses as $course)
                <tr class="intro-x">
                    <td class="w-40">
                        <div class="flex items-center justify-center">
                            {{ $course->title }}
                        </div>
                    </td>
                    <td class="w-40">
                        <div class="flex items-center justify-center">
                            {{ $course->code }}
                        </div>
                    </td>
                    <td>
                        <a href="" class="font-medium whitespace-nowrap">{{ $course->instructor->fname.' '.$course->instructor->lname }}</a>
                        <div class="text-gray-600 text-xs whitespace-nowrap mt-0.5">{{ $course->instructor->provider['name'] }}</div>
                    </td>
                    <td class="text-center">{{ $course->created_at->format('d-m-Y') }}</td>
                    <td class="table-report__action w-56">
                        <div class="flex justify-center items-center">
                            <a class="flex items-center mr-3" href="{{ route('portal.instructor.course.edit', $course->id) }}"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit </a>
                            <a class="flex items-center text-theme-6" href="javascript:;" data-toggle="modal" data-target="#delete-confirmation-modal{{ $course->id }}"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </a>
                        </div>
                    </td>
                </tr>
                    @push('delete-modal')
                        @include('portal.lecturer.inc.course-delete-modal', $course)
                    @endpush
                @empty
                    <div class="alert alert-danger alert-dismissible show flex items-center mb-2">
                        <i data-feather="alert-octagon" class="w-6 h-6 mr-2"></i> Oops!! No course found.
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> <i data-feather="x" class="w-4 h-4"></i> </button>
                    </div>
                @endforelse
            </tbody>
        </table>
    </div>
@if(count($courses) > 0)
    <!-- END: Data List -->
    <!-- BEGIN: Pagination -->
    <div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-nowrap items-center">
        <ul class="pagination">
            {!! $courses->links() !!}
        </ul>
        <select class="w-20 form-select box mt-3 sm:mt-0">
            <option>10</option>
            <option>25</option>
            <option>35</option>
            <option>50</option>
        </select>
    </div>
@endif
    <!-- END: Pagination -->
</div>

@endsection

resources/views/portal/lecturer/create-course.blade.php
@extends('portal.lecturer.layout')
@if($course->id)
    @section('title', $course->title)
@else
    @section('title', 'Add Course')
@endif
@section('content')
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
        <a href="{{ route('portal.instructor.course.home') }}" class="btn btn-primary shadow-md mr-2"> <i class="bx bx-left-arrow-alt"></i> All Courses</a>
        </div>
        <div class="row col-span-12">
        </div>
        <form class="intro-y col-span-12 lg:col-span-8"
              @if($course->id) action="{{ route('portal.instructor.course.update', $course->id) }}" @else action="{{ route('portal.instructor.course.store') }}" @endif
              method="POST">
            @csrf
            @if($course->id)
                @method('PATCH')
            @endif
            <!-- BEGIN: Form Layout -->
            <div class="intro-y box p-5">
                @include('portal.lecturer.inc.alert')
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">Course Title</label>
                    <input id="crud-form-1" value="{{ old('title', $course->title) }}" type="text" class="form-control w-full" name="title" placeholder="Use Of English">
                </div>
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">Course Code</label>
                    <input id="crud-form-1" type="text" value="{{ old('code', $course->code) }}" class="form-control w-full" name="code" placeholder="ENG101">
                </div>
                <div class="text-right mt-5">
                    <button type="submit" class="btn btn-primary w-44">Save</button>
                </div>
            </div>
            <!-- END: Form Layout -->
        </form>
    </div>
@endsection

resources/views/portal/lecturer/layout.blade.php
<!DOCTYPE html>
<html lang="en" class="light">
<head>
    <meta charset="utf-8">
    <title>@yield('title') - {{ $appName }}</title>
@include('portal.lecturer.inc.styles')
<!-- END: CSS Assets-->
</head>

<!-- END: Head -->
<body class="main">
@include('portal.lecturer.inc.msidebar')
<div class="flex">
@include('portal.lecturer.inc.sidebar')
<!-- BEGIN: Content -->
    <div class="content">
        @include('portal.lecturer.inc.navbar')
        @yield('content')
    </div>
    <!-- END: Content -->
</div>

@stack('delete-modal')
<!-- END: Dark Mode Switcher-->
@include('portal.lecturer.inc.scripts')
@yield('scripts')
</body>
</html>