routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.index');
});

Auth::routes();

// Admin Routes
Route::middleware('auth')->name('portal.')->prefix('portal')->group(function () {
    Route::get('/', 'PortalController@index')->name('home');
    Route::prefix('admin')->name('admin.')->middleware('admin')->group( function(){
        Route::get('/', 'AdminController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('provider')->name('provider.')->group( function() {
            Route::get('/', 'AdminController@providers')->name('home');
            Route::get('create', 'AdminController@create')->name('create');
            Route::get('edit/{provider}', 'AdminController@edit')->name('edit');
            Route::post('store', 'AdminController@store')->name('store');
            Route::patch('update/{provider}', 'AdminController@update')->name('update');
            Route::get('delete/{provider}', 'AdminController@destroy')->name('delete');
        });
    });

    // Provider Routes
    Route::prefix('provider')->name('provider.')->middleware('provider')->group( function(){
        Route::get('/', 'ProviderController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('lecturer')->name('lecturer.')->group( function() {
            Route::get('/', 'ProviderController@lecturers')->name('home');
            Route::get('create', 'ProviderController@create')->name('create');
            Route::get('edit/{lecturer}', 'ProviderController@edit')->name('edit');
            Route::post('store', 'ProviderController@store')->name('store');
            Route::patch('update/{lecturer}', 'ProviderController@update')->name('update');
            Route::get('delete/{lecturer}', 'ProviderController@destroy')->name('delete');

            Route::get('activate/{lecturer}', 'ProviderController@activate')->name('activate');
            Route::get('deactivate/{lecturer}', 'ProviderController@deactivate')->name('deactivate');
        });
        Route::prefix('student')->name('student.')->group( function() {
            Route::get('/', 'ProviderController@students')->name('home');
            Route::get('edit/{student}', 'ProviderController@editStudent')->name('edit');
            Route::get('requests', 'ProviderController@studentRequests')->name('requests');
            Route::patch('update/{student}', 'ProviderController@updateStudent')->name('update');
            Route::get('delete/{student}', 'ProviderController@destroyStudent')->name('delete');

            Route::get('activate/{student}', 'ProviderController@activateStudent')->name('activate');
            Route::get('deactivate/{student}', 'ProviderController@deactivateStudent')->name('deactivate');
        });
    });

    // Student Routes
    Route::prefix('student')->name('student.')->middleware('student')->group( function() {
        Route::get('/', 'StudentController@index')->name('home');
        Route::get('/scans', 'StudentController@scans')->name('scans');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('assignment')->name('assignment.')->group( function() {
            Route::get('/', 'StudentController@assignments')->name('home');
            Route::get('/submission/{assignment}', 'StudentController@submission')->name('submission');
            Route::get('/submit/{assignment}', 'StudentController@submitAssignment')->name('submit');
            Route::post('/scan/{assignment}', 'StudentController@scanAssignment')->name('scan');
        });
    });
    // Instructor Routes
    Route::prefix('instructor')->name('instructor.')->middleware('instructor')->group( function() {
        Route::get('/', 'LecturerController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::get('/scans', 'LecturerController@scans')->name('scans');
        Route::prefix('assignment')->name('assignment.')->group( function() {
            Route::get('/', 'LecturerController@assignments')->name('home');
            Route::get('/create', 'LecturerController@createAssignment')->name('create');
            Route::get('/edit/{assignment}', 'LecturerController@createAssignment')->name('edit');
            Route::post('/store', 'LecturerController@storeAssignment')->name('store');
            Route::patch('/update/{assignment}', 'LecturerController@updateAssignment')->name('update');
            Route::get('/delete/{assignment}', 'LecturerController@destroyAssignment')->name('delete');
            Route::post('/scan/{assignment}', 'LecturerController@scanAssignment')->name('scan');
        });
        Route::prefix('course')->name('course.')->group( function() {
            Route::get('/', 'LecturerController@courses')->name('home');
            Route::get('/create', 'LecturerController@createCourse')->name('create');
            Route::post('/store', 'LecturerController@storeCourse')->name('store');
            Route::get('/edit/{course}', 'LecturerController@createCourse')->name('edit');
            Route::patch('/update/{course}', 'LecturerController@updateCourse')->name('update');
            Route::get('/delete/{course}', 'LecturerController@destroyCourse')->name('delete');
        });
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Lecturer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Lecturer extends Model
{
    use HasFactory;

    protected $primaryKey = 'user_id';
    protected $table = 'users';

    public function courses()
    {
        return $this->hasMany(Course::class, 'user_id');
    }
}

app/Models/Provider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Provider extends Model
{
    use HasFactory, SoftDeletes;

    protected $primaryKey = 'provider_id';
    protected $guarded = [];

    protected $casts = [
        'starts_at' => 'datetime',
        'expires_at' => 'datetime',
    ];
    public function scopeActive($query)
    {
        return $query->where(['status' => '2'])->where('starts_at', '<', now())->where('expires_at', '>=', now());
    }

    public function user()
    {
        return $this->hasMany(User::class, 'provider_id');
    }
}

app/Http/Controllers/LecturerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Assignment;
use App\Models\Course;
use App\Models\Lecturer;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

class LecturerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('portal.lecturer.index');
    }

    public function courses()
    {
        $courses = Course::owner()->paginate(20);
        return view('portal.lecturer.courses', compact('courses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function createCourse(Course $course)
    {
        return view('portal.lecturer.create-course', ['course' => $course]);
    }
    public function storeCourse(Request $request)
    {
        $course = Course::whereCode($request->code)->first();
        if ($course){
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Duplicate Course Code.']);
        }
        $course_create = Course::create([
            'title' => $request->title,
            'code' => $request->code,
            'user_id' => \Auth::id(),
        ]);
        if ($course_create) {
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Course added successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }
    }
    public function updateCourse(Request $request, Course $course)
    {
        $update = $course->update([
            'title' => $request->title,
            'code' => $request->code,
            'user_id' => \Auth::id(),
        ]);
        if ($update) {
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Course updated successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function assignments()
    {
        $assignments = Assignment::whereUser_id(\Auth::id())->paginate(20);
        return view('portal.lecturer.assignments', compact('assignments'));
    }
    public function createAssignment(Assignment $assignment)
    {
        return view('portal.lecturer.create-assignment', compact('assignment'));
    }

    public function storeAssignment(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|string|min:3',
            'course' => 'required|string',
            'start_date' => 'required',
            'end_date' => 'required',
        ]);
        if ($validator->fails()){
            return redirect()->back()->withInput()->withErrors($validator->errors());
        }
        $input = $request->all();
        $input['user_id'] = \Auth::id();
        $input['status'] = '1';
        $input['start_date'] = Carbon::parse($request->start_date)->format('Y-m-d');
        $input['end_date'] = Carbon::parse($request->end_date)->format('Y-m-d');
        $save = Assignment::create($input);
        if ($save){
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Assignment created successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function show(Lecturer $lecturer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function edit(Lecturer $lecturer)
    {
        return view('portal.lecturer.create-assignment', compact('assignment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function updateAssignment(Request $request, Assignment $assignment)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|string|min:3',
            'course' => 'required|string',
            'start_date' => 'required',
            'end_date' => 'required',
        ]);
        if ($validator->fails()){
            return redirect()->back()->withInput()->withErrors($validator->errors());
        }
        $assignment->title = $request->title;
        $assignment->course = $request->course;
        $assignment->group_by = $request->group_by;
        $assignment->nwords = $request->nwords;
        $assignment->group_by = $request->group_by;
        $assignment->submit_before_end = $request->submit_before_end;
        $assignment->repo_source = $request->repo_source;
        $assignment->show_rel = $request->show_rel;
        $assignment->start_date = Carbon::parse($request->start_date)->format('Y-m-d');
        $assignment->end_date = Carbon::parse($request->end_date)->format('Y-m-d');

        if ($assignment->save()){
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Assignment updated successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lecturer $lecturer)
    {
        //
    }
    public function destroyAssignment(Assignment $assignment )
    {
        if ($assignment->delete()) {
            return Redirect::back()->with([ 'message' => "Assignment Deleted Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with([ 'message' => "Oops! Provider not deleted.", 'error' => true]);
        }
    }
    public function destroyCourse(Course $course )
    {
        if ($course->delete()) {
            return Redirect::back()->with([ 'message' => "Course Deleted Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with([ 'message' => "Oops! Provider not deleted.", 'error' => true]);
        }
    }
}

resources/views/portal/provider/lecturers/create.blade.php
@extends('portal.provider.layout')
@section('title', 'Create New Lecturers')
@section('content')
    <div class="grid grid-cols-12 gap-6 mt-5">
        <form class="intro-y col-span-12 lg:col-span-8" method="POST" action="{{ route('portal.provider.lecturer.store') }}">
            @include('portal.provider.inc.alert')
            @csrf
            <!-- BEGIN: Form Layout -->
            <div class="intro-y box p-5">
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">Title</label>
                    <input id="crud-form-1" type="text" class="form-control w-full" name="provider_title" placeholder="Dr.">
                </div>
                <div class="sm:grid grid-cols-2 gap-2 my-5">
                    <div class="">
                        <label for="crud-form-1" class="form-label">First Name</label>
                        <input id="crud-form-1" type="text" class="form-control w-full" name="fname" placeholder="John">
                    </div>
                    <div class="">
                        <label for="crud-form-1" class="form-label">Last Name</label>
                        <input id="crud-form-1" type="text" class="form-control w-full" name="lname" placeholder="Doe">
                    </div>
                </div>
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">Username</label>
                    <input id="crud-form-1" type="text" class="form-control w-full" name="username" placeholder="johndoe">
                </div>
                <div class="sm:grid grid-cols-2 gap-2 my-5">
                    <div class="">
                        <label for="crud-form-1" class="form-label">Email Address</label>
                        <input id="crud-form-1" type="email" class="form-control w-full" name="email" placeholder="johndoe@example.com">
                    </div>
                    <div class="">
                        <label for="crud-form-1" class="form-label">Phone Number</label>
                        <input id="crud-form-1" type="tel" class="form-control w-full" name="tel" placeholder="+234808989009">
                    </div>
                </div>
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">Faculty/School</label>
                    <input id="crud-form-1" type="text" class="form-control w-full" name="faculty" placeholder="Faculty of Science">
                </div>
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">School ID/Number</label>
                    <input id="crud-form-1" type="text" class="form-control w-full" name="school_id" placeholder="HLE.2019/SC456">
                </div>
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">Department</label>
                    <input id="crud-form-1" type="text" class="form-control w-full " name="dept" placeholder="Computer Science">
                </div>
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">Password</label>
                    <input id="crud-form-1" type="password" class="form-control w-full " name="password" placeholder="Lecturer Password">
                </div>
                <div class="mt-3">
                    <label>Active Status</label>
                    <div class="mt-2">
                        <input type="checkbox" value="2" name="status" class="form-check-switch">
                    </div>
                </div>
                <div class="text-right mt-5">
                    <button type="button" class="btn btn-outline-secondary w-24 mr-1">Cancel</button>
                    <button type="submit" class="btn btn-primary w-24">Save</button>
                </div>
            </div>
            <!-- END: Form Layout -->
        </form>
    </div>
@endsection

resources/views/portal/provider/lecturers/edit.blade.php
@extends('portal.provider.layout')
@section('title', $lecturer->provider_title.' '.$lecturer->fname.' '.$lecturer->lname)
@section('content')
    <div class="grid grid-cols-12 gap-6 mt-5">
        <form class="intro-y col-span-12 lg:col-span-8" method="POST" action="{{ route('portal.provider.lecturer.update', $lecturer->user_id) }}">
            <div class="alert @if (Session::has('success')) alert-success @elseif(Session::has('error')) alert-danger @else d-none @endif alert-dismissible show flex items-center mb-2" role="alert">
                @if(Session::has('success')) <i data-feather="alert-circle" class="w-6 h-6 mr-2"></i> @elseif(Session::has('error'))  <i data-feather="alert-octagon" class="w-6 h-6 mr-2"></i> @endif {{ Session::get('message') }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> <i data-feather="x" class="w-4 h-4"></i> </button>
            </div>
            @csrf
            @method('PATCH')
        <!-- BEGIN: Form Layout -->
            <div class="intro-y box p-5">
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">Title</label>
                    <input id="crud-form-1" type="text" class="form-control w-full" value="{{ old('provider_title', $lecturer->provider_title) }}" name="provider_title" placeholder="Dr.">
                </div>
                <div class="sm:grid grid-cols-2 gap-2 my-5">
                    <div class="">
                        <label for="crud-form-1" class="form-label">First Name</label>
                        <input id="crud-form-1" type="text" class="form-control w-full" value="{{ old('fname', $lecturer->fname) }}" name="fname" placeholder="John">
                    </div>
                    <div class="">
                        <label for="crud-form-1" class="form-label">Last Name</label>
                        <input id="crud-form-1" type="text" class="form-control w-full" value="{{ old('lname', $lecturer->lname) }}" name="lname" placeholder="Doe">
                    </div>
                </div>
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">Username</label>
                    <input id="crud-form-1" type="text" class="form-control w-full" value="{{ old('username', $lecturer->username) }}" name="username" placeholder="johndoe">
                </div>
                <div class="sm:grid grid-cols-2 gap-2 my-5">
                    <div class="">
                        <label for="crud-form-1" class="form-label">Email Address</label>
                        <input id="crud-form-1" type="email" class="form-control w-full" value="{{ old('email', $lecturer->email) }}" name="email" placeholder="johndoe@example.com">
                    </div>
                    <div class="">
                        <label for="crud-form-1" class="form-label">Phone Number</label>
                        <input id="crud-form-1" type="tel" class="form-control w-full" value="{{ old('tel', $lecturer->tel) }}" name="tel" placeholder="+234808989009">
                    </div>
                </div>
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">Faculty/School</label>
                    <input id="crud-form-1" type="text" class="form-control w-full" name="faculty" value="{{ old('faculty', $lecturer->faculty) }}" placeholder="Faculty of Science">
                </div>
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">School ID/Number</label>
                    <input id="crud-form-1" type="text" class="form-control w-full" name="school_id" value="{{ old('school_id', $lecturer->school_id) }}" placeholder="HLE.2019/SC456">
                </div>
                <div class="my-5">
                    <label for="crud-form-1" class="form-label">Department</label>
                    <input id="crud-form-1" type="text" class="form-control w-full " name="dept" value="{{ old('dept', $lecturer->dept) }}" placeholder="Computer Science">
                </div>
                <div class="mt-3">
                    <label>Active Status</label>
                    <div class="mt-2">
                        <input type="checkbox" value="2" name="status" @if (old('status', $lecturer->status) == '2') checked @endif class="form-check-switch">
                    </div>
                </div>
                <div class="text-right mt-5">
                    <button type="button" class="btn btn-outline-secondary w-24 mr-1">Cancel</button>
                    <button type="submit" class="btn btn-primary w-24">Save</button>
                </div>
            </div>
            <!-- END: Form Layout -->
        </form>
    </div>
@endsection

resources/views/portal/provider/lecturers/index.blade.php
@extends('portal.provider.layout')
@section('title', 'All Lecturers')
@section('content')
    <div class="intro-y flex items-center mt-8">
        <h2 class="text-lg font-medium mr-auto">
            @yield('title')
        </h2>
    </div>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-nowrap items-center mt-2">
            <a href="{{ route('portal.provider.lecturer.create') }}" class="btn btn-primary shadow-md mr-2">Add New Lecturer</a>
            <div class="dropdown">
                <button class="dropdown-toggle btn px-2 box text-gray-700 dark:text-gray-300" aria-expanded="false">
                    <span class="w-5 h-5 flex items-center justify-center"> <i class="w-4 h-4" data-feather="plus"></i> </span>
                </button>
                <div class="dropdown-menu w-40">
                    <div class="dropdown-menu__content box dark:bg-dark-1 p-2">
                        <a href="" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md"> <i data-feather="printer" class="w-4 h-4 mr-2"></i> Print </a>
                        <a href="" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md"> <i data-feather="file-text" class="w-4 h-4 mr-2"></i> Export to Excel </a>
                        <a href="" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md"> <i data-feather="file-text" class="w-4 h-4 mr-2"></i> Export to PDF </a>
                    </div>
                </div>
            </div>
            <div class="hidden md:block mx-auto text-gray-600">Showing 1 to 2 of 2 entries</div>
            <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
                <div class="w-56 relative text-gray-700 dark:text-gray-300">
                    <input type="text" class="form-control w-56 box pr-10 placeholder-theme-13" placeholder="Search...">
                    <i class="w-4 h-4 absolute my-auto inset-y-0 mr-3 right-0" data-feather="search"></i>
                </div>
            </div>
        </div>
        <!-- BEGIN: Data List -->
        <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
            @include('portal.provider.inc.alert')
            @if (count($lecturers) > 0)

            <table class="table table-report -mt-2">
                <thead>
                <tr>
                    <th class="whitespace-nowrap">S/N</th>
                    <th class="whitespace-nowrap">Instructor</th>
                    <th class="text-center whitespace-nowrap">Username</th>
                    <th class="text-center whitespace-nowrap">Email</th>
                    <th class="text-center whitespace-nowrap">Status</th>
                    <th class="text-center whitespace-nowrap">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($lecturers as $l)
                <tr class="intro-x">
                    <td class="w-10">
                        <div class="flex items-left justify-left">
                            #{{ $l->user_id }}
                        </div>
                    </td>
                    <td>
                        <a href="" class="font-medium whitespace-nowrap">{{ $l->provider_title.' '.$l->fname.' '.$l->lname }}</a>
                        <div class="text-gray-600 text-xs whitespace-nowrap mt-0.5">{{ $l->dept }}</div>
                    </td>
                    <td class="text-center">{{ $l->username }}</td>
                    <td class="w-40">
                        <div class="flex items-center justify-center "> {{ $l->email }} </div>
                    </td>
                    <td class="w-40">
                        <div class="flex items-center justify-center pill pill-success">
                            @if ($l->status == '0')
                                <span class="px-2 py-1 rounded-full bg-theme-6 text-white mr-1">Deactive</span>
                            @else
                                <span class="px-2 py-1 rounded-full bg-theme-9 text-white mr-1">Active</span>
                            @endif
                        </div>
                    </td>
                    <td class="table-report__action w-56">
                        <div class="flex justify-center items-center">
                            <a class="flex items-center mr-3" href="{{ route('portal.provider.lecturer.edit', $l->user_id) }}"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit </a>
                            @if ((int)$l->status < 1)
                                <a class="flex items-center mr-3" href="{{ route('portal.provider.lecturer.activate', $l->user_id) }}"> <i data-feather="eye" class="w-4 h-4 mr-1"></i> Activate </a>
                            @else
                                <a class="flex items-center mr-3" href="{{ route('portal.provider.lecturer.deactivate', $l->user_id) }}"> <i data-feather="eye-off" class="w-4 h-4 mr-1"></i> Deactivate </a>
                            @endif
                            <a class="flex items-center text-theme-6" href="javascript:;" data-toggle="modal" data-target="#delete-confirmation-modal{{ $l->user_id }}"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete </a>
                        </div>
                    </td>
                </tr>
                @push('delete-modal')
                    @include('portal.provider.inc.lecturer-delete-modal', ['l' => $l])
                @endpush
                @endforeach
                </tbody>
            </table>
            @else
                <div class="alert alert-danger alert-dismissible show flex items-center mb-2" role="alert">
                    <i data-feather="alert-octagon" class="w-6 h-6 mr-2"></i> Oops!! No Client Record Found.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> <i data-feather="x" class="w-4 h-4"></i> </button>
                </div>
            @endif

        </div>
        <!-- END: Data List -->
        <!-- BEGIN: Pagination -->
        @if (count($lecturers) > 0)
        <div class="intro-y col-span-12 flex flex-wrap sm:flex-row sm:flex-nowrap items-center">
            <ul class="pagination">
               {!! $lecturers->links() !!}
            </ul>
            <select class="w-20 form-select box mt-3 sm:mt-0">
                <option>10</option>
                <option>25</option>
                <option>35</option>
                <option>50</option>
            </select>
        </div>
        @endif
        <!-- END: Pagination -->
    </div>
@endsection