routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.index');
});

Auth::routes();

// Admin Routes
Route::middleware('auth')->name('portal.')->prefix('portal')->group(function () {
    Route::get('/', 'PortalController@index')->name('home');
    Route::prefix('admin')->name('admin.')->middleware('admin')->group( function(){
        Route::get('/', 'AdminController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('provider')->name('provider.')->group( function() {
            Route::get('/', 'AdminController@providers')->name('home');
            Route::get('create', 'AdminController@create')->name('create');
            Route::get('edit/{provider}', 'AdminController@edit')->name('edit');
            Route::post('store', 'AdminController@store')->name('store');
            Route::patch('update/{provider}', 'AdminController@update')->name('update');
            Route::get('delete/{provider}', 'AdminController@destroy')->name('delete');
        });
    });

    // Provider Routes
    Route::prefix('provider')->name('provider.')->middleware('provider')->group( function(){
        Route::get('/', 'ProviderController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('lecturer')->name('lecturer.')->group( function() {
            Route::get('/', 'ProviderController@lecturers')->name('home');
            Route::get('create', 'ProviderController@create')->name('create');
            Route::get('edit/{lecturer}', 'ProviderController@edit')->name('edit');
            Route::post('store', 'ProviderController@store')->name('store');
            Route::patch('update/{lecturer}', 'ProviderController@update')->name('update');
            Route::get('delete/{lecturer}', 'ProviderController@destroy')->name('delete');

            Route::get('activate/{lecturer}', 'ProviderController@activate')->name('activate');
            Route::get('deactivate/{lecturer}', 'ProviderController@deactivate')->name('deactivate');
        });
        Route::prefix('student')->name('student.')->group( function() {
            Route::get('/', 'ProviderController@students')->name('home');
            Route::get('edit/{student}', 'ProviderController@editStudent')->name('edit');
            Route::get('requests', 'ProviderController@studentRequests')->name('requests');
            Route::patch('update/{student}', 'ProviderController@updateStudent')->name('update');
            Route::get('delete/{student}', 'ProviderController@destroyStudent')->name('delete');

            Route::get('activate/{student}', 'ProviderController@activateStudent')->name('activate');
            Route::get('deactivate/{student}', 'ProviderController@deactivateStudent')->name('deactivate');
        });
    });

    // Student Routes
    Route::prefix('student')->name('student.')->middleware('student')->group( function() {
        Route::get('/', 'StudentController@index')->name('home');
        Route::get('/scans', 'StudentController@scans')->name('scans');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('assignment')->name('assignment.')->group( function() {
            Route::get('/', 'StudentController@assignments')->name('home');
            Route::get('/submission/{assignment}', 'StudentController@submission')->name('submission');
            Route::get('/submit/{assignment}', 'StudentController@submitAssignment')->name('submit');
            Route::post('/scan/{assignment}', 'StudentController@scanAssignment')->name('scan');
        });
    });
    // Instructor Routes
    Route::prefix('instructor')->name('instructor.')->middleware('instructor')->group( function() {
        Route::get('/', 'LecturerController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::get('/scans', 'LecturerController@scans')->name('scans');
        Route::prefix('assignment')->name('assignment.')->group( function() {
            Route::get('/', 'LecturerController@assignments')->name('home');
            Route::get('/create', 'LecturerController@createAssignment')->name('create');
            Route::get('/edit/{assignment}', 'LecturerController@createAssignment')->name('edit');
            Route::post('/store', 'LecturerController@storeAssignment')->name('store');
            Route::patch('/update/{assignment}', 'LecturerController@updateAssignment')->name('update');
            Route::get('/delete/{assignment}', 'LecturerController@destroyAssignment')->name('delete');
            Route::post('/scan/{assignment}', 'LecturerController@scanAssignment')->name('scan');
        });
        Route::prefix('course')->name('course.')->group( function() {
            Route::get('/', 'LecturerController@courses')->name('home');
            Route::get('/create', 'LecturerController@createCourse')->name('create');
            Route::post('/store', 'LecturerController@storeCourse')->name('store');
            Route::get('/edit/{course}', 'LecturerController@createCourse')->name('edit');
            Route::patch('/update/{course}', 'LecturerController@updateCourse')->name('update');
            Route::get('/delete/{course}', 'LecturerController@destroyCourse')->name('delete');
        });
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Provider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Provider extends Model
{
    use HasFactory, SoftDeletes;

    protected $primaryKey = 'provider_id';
    protected $guarded = [];

    protected $casts = [
        'starts_at' => 'datetime',
        'expires_at' => 'datetime',
    ];
    public function scopeActive($query)
    {
        return $query->where(['status' => '2'])->where('starts_at', '<', now())->where('expires_at', '>=', now());
    }

    public function user()
    {
        return $this->hasMany(User::class, 'provider_id');
    }
}

app/Http/Controllers/ProviderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Provider;
use App\Models\User as Lecturer;
use App\Models\User as Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Redirect;

class ProviderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('portal.provider.index');
    }

    public function lecturers()
    {
        $provider = \Auth::user()->provider_id;
        $lecturers = Lecturer::whereLevel('1')->whereProvider_id($provider)->paginate(20);
        return view('portal.provider.lecturers.index', compact('lecturers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('portal.provider.lecturers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $input = $request->all();
        $input['provider_role'] = 'Lecturer';
        $input['level'] = '1';
        $input['provider_id'] = \Auth::user()->provider_id;
        $input['password'] = Hash::make($request->password);
        $save = Lecturer::create($input);

        if ($save) {
            return Redirect::back()->with([ 'message' => "Lecturer Created Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with(['message' => "Oops! Something went wrong.", 'error' => true]);
        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Provider  $provider
     * @return \Illuminate\Http\Response
     */
    public function edit(Lecturer $lecturer)
    {
        return view('portal.provider.lecturers.edit', compact('lecturer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Provider  $provider
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Lecturer $lecturer)
    {
        $input = $request->except('_token', 'method');
        if ($request->status == '') {
            $input['status'] = '0';
        }
        $save = $lecturer->update($input);

        if ($save) {
            return Redirect::back()->with([ 'message' => "Lecturer Updated Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with(['message' => "Oops! Something went wrong.", 'error' => true]);
        }
    }

    public function activate(Request $request, Lecturer $lecturer)
    {
        $save = $lecturer->update([
            'status' => '2'
        ]);

        if ($save) {
            return Redirect::back()->with([ 'message' => "Lecturer Activated Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with(['message' => "Oops! Something went wrong.", 'error' => true]);
        }
    }
    public function deactivate(Request $request, Lecturer $lecturer)
    {
        $save = $lecturer->update([
            'status' => '0'
        ]);

        if ($save) {
            return Redirect::back()->with([ 'message' => "Lecturer Deactivated Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with(['message' => "Oops! Something went wrong.", 'error' => true]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Provider  $provider
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lecturer $lecturer)
    {
        if ($lecturer->delete()) {
            return Redirect::back()->with([ 'message' => "Provider Deleted Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with([ 'message' => "Oops! Provider not deleted.", 'error' => true]);
        }
    }

    // Student Methods

    public function students()
    {
        $provider = \Auth::user()->provider_id;
        $students = Student::whereLevel('0')->whereProvider_id($provider)->paginate(20);
        return view('portal.provider.students.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function studentRequests()
    {
        $provider = \Auth::user()->provider_id;
        $students = Student::whereLevel('0')->whereStatus('0')->whereProvider_id($provider)->paginate(20);
        return view('portal.provider.students.requests', compact('students'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Provider  $provider
     * @return \Illuminate\Http\Response
     */
    public function editStudent(Student $student)
    {
        return view('portal.provider.lecturers.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Provider  $provider
     * @return \Illuminate\Http\Response
     */
    public function updateStudent(Request $request, Student $student)
    {
        $input = $request->except('_token', 'method');
        if ($request->status == '') {
            $input['status'] = '0';
        }
        $save = $student->update($input);

        if ($save) {
            return Redirect::back()->with([ 'message' => "Student Updated Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with(['message' => "Oops! Something went wrong.", 'error' => true]);
        }
    }

    public function activateStudent(Request $request, Student $student)
    {
        $save = $student->update([
            'status' => '2'
        ]);

        if ($save) {
            return Redirect::back()->with([ 'message' => "Student Activated Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with(['message' => "Oops! Something went wrong.", 'error' => true]);
        }
    }
    public function deactivateStudent(Request $request, Student $student)
    {
        $save = $student->update([
            'status' => '0'
        ]);

        if ($save) {
            return Redirect::back()->with([ 'message' => "Student Deactivated Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with(['message' => "Oops! Something went wrong.", 'error' => true]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Provider  $provider
     * @return \Illuminate\Http\Response
     */
    public function destroyStudent(Student $student)
    {
        if ($student->delete()) {
            return Redirect::back()->with([ 'message' => "Student Deleted Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with([ 'message' => "Oops! Provider not deleted.", 'error' => true]);
        }
    }
}

resources/views/portal/provider/inc/alert.blade.php
<div class="alert @if (Session::has('success')) alert-success @elseif(Session::has('error')) alert-danger @else d-none @endif alert-dismissible show flex items-center mb-2" role="alert">
    @if(Session::has('success')) <i data-feather="alert-circle" class="w-6 h-6 mr-2"></i> @elseif(Session::has('error'))  <i data-feather="alert-octagon" class="w-6 h-6 mr-2"></i> @endif {{ Session::get('message') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> <i data-feather="x" class="w-4 h-4"></i> </button>
</div>

resources/views/portal/provider/inc/lecturer-delete-modal.blade.php
<!-- BEGIN: Delete Confirmation Modal -->
<div id="delete-confirmation-modal{{ $l->user_id }}" class="modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body p-0">
                <div class="p-5 text-center">
                    <i data-feather="x-circle" class="w-16 h-16 text-theme-6 mx-auto mt-3"></i>
                    <div class="text-3xl mt-5">Are you sure?</div>
                    <div class="text-gray-600 mt-2">
                        Do you really want to delete {{ $l->provider_title.' '.$l->fname.' '.$l->lname }} records?
                        <br>
                        This process cannot be undone.
                    </div>
                </div>
                <div class="px-5 pb-8 text-center">
                    <button type="button" data-dismiss="modal" class="btn btn-outline-secondary w-24 mr-1">Cancel</button>
                    <a href="{{ route('portal.provider.lecturer.delete', $l->user_id) }}" class="btn btn-danger w-24">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END: Delete Confirmation Modal -->

resources/views/portal/provider/inc/msidebar.blade.php
<!-- BEGIN: Mobile Menu -->
<div class="mobile-menu md:hidden">
    <div class="mobile-menu-bar">
        <a href="" class="flex mr-auto">
            <img alt="Verify Project" class="w-50" style="width: 30%;" src="{{ asset('dist/images/logo-w.png') }}">
        </a>
        <a href="javascript:;" id="mobile-menu-toggler"> <i data-feather="bar-chart-2" class="w-8 h-8 text-white transform -rotate-90"></i> </a>
    </div>
    <ul class="border-t border-theme-29 py-5 hidden">
        <li>
            <a href="{{ route('portal.provider.home') }}" class="menu @if(\Route::current()->getName() == 'portal.provider.home') menu--active @endif">
                <div class="menu__icon"> <i data-feather="home"></i> </div>
                <div class="menu__title">
                    Dashboard
                </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.provider.lecturer.create') }}" class="menu @if(\Route::current()->getName() == 'portal.provider.lecturer.create') menu--active @endif">
                <div class="menu__icon"> <i data-feather="user-plus"></i> </div>
                <div class="menu__title">  Create Lecturer </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.provider.lecturer.home') }}" class="menu @if(\Route::current()->getName() == 'portal.provider.lecturer.home') menu--active @endif">
                <div class="menu__icon"> <i data-feather="users"></i> </div>
                <div class="menu__title"> Manage Lecturers </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.provider.student.home') }}" class="menu @if(\Route::current()->getName() == 'portal.provider.student.home') menu--active @endif">
                <div class="menu__icon"> <i data-feather="users"></i> </div>
                <div class="menu__title"> Manage Students </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.provider.student.requests') }}" class="menu @if(\Route::current()->getName() == 'portal.provider.student.requests') menu--active @endif">
                <div class="menu__icon"> <i data-feather="user-check"></i> </div>
                <div class="menu__title"> Registration Requests </div>
            </a>
        </li>
        <li>
            <a href="./all-scans.php" class="menu <?php if(isset($page) && $page == 'all-scans'){ echo 'menu--active'; } ?>">
                <div class="menu__icon"> <i data-feather="search"></i> </div>
                <div class="menu__title"> My Scans </div>
            </a>
        </li>
        <li>
            <a href="./search-repository.php" class="menu <?php if(isset($page) && $page == 'search-repo'){ echo 'menu--active'; } ?>">
                <div class="menu__icon"> <i data-feather="zoom-in"></i> </div>
                <div class="menu__title"> Search Repository </div>
            </a>
        </li>
        <li>
            <a href="javascript:;" class="menu <?php if(isset($page) && $page == 'repo'){ echo 'menu--active'; } ?>">
                <div class="menu__icon"> <i data-feather="database"></i> </div>
                <div class="menu__title">
                    Repository
                    <div class="menu__sub-icon"> <i data-feather="chevron-down"></i> </div>
                </div>
            </a>
            <ul class="">
                <li>
                    <a href="./repository.php" class="menu">
                        <div class="menu__icon"> <i data-feather="file-text"></i> </div>
                        <div class="menu__title"> My Documents </div>
                    </a>
                </li>
                <li>
                    <a href="./categories.php" class="menu">
                        <div class="menu__icon"> <i data-feather="list"></i> </div>
                        <div class="menu__title"> Categories </div>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:;" class="menu @route('portal.provider.account*') menu--active @endroute">
                <div class="menu__icon"> <i data-feather="settings"></i> </div>
                <div class="menu__title">
                    Account
                    <div class="menu__sub-icon"> <i data-feather="chevron-down"></i> </div>
                </div>
            </a>
            <ul class="">
                <li>
                    <a href="{{ route('portal.provider.account.password.change') }}" class="menu">
                        <div class="menu__icon"> <i data-feather="lock"></i> </div>
                        <div class="menu__title"> Change Password </div>
                    </a>
                </li>
                <li>
                    <a href="./profile.php" class="menu">
                        <div class="menu__icon"> <i data-feather="user"></i> </div>
                        <div class="menu__title"> Update Profile </div>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</div>
<!-- END: Mobile Menu -->

resources/views/portal/provider/inc/scripts.blade.php
<!-- BEGIN: JS Assets-->
<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=0&libraries=places"></script>
<script src="{{ asset('dist/js/app.js') }}"></script>
<!-- END: JS Assets-->

resources/views/portal/provider/inc/sidebar.blade.php
<!-- BEGIN: Side Menu -->
<nav class="side-nav">
    <a href="" class="intro-x flex items-center pl-5 pt-4">
        <img alt="Verify Project" class="w-50" style="width: 70%;" src="{{ asset('dist/images/logo-w.png') }}">
    </a>
    <div class="side-nav__devider my-6"></div>
    <ul>
        <li>
            <a href="{{ route('portal.provider.home') }}" class="side-menu @if(\Route::current()->getName() == 'portal.provider.home') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="home"></i> </div>
                <div class="side-menu__title">
                    Dashboard
                </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.provider.lecturer.create') }}" class="side-menu @if(\Route::current()->getName() == 'portal.provider.lecturer.create') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="user-plus"></i> </div>
                <div class="side-menu__title">  Create Lecturer </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.provider.lecturer.home') }}" class="side-menu @if(\Route::current()->getName() == 'portal.provider.lecturer.home') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="users"></i> </div>
                <div class="side-menu__title"> Manage Lecturers </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.provider.student.home') }}" class="side-menu @if(\Route::current()->getName() == 'portal.provider.student.home') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="users"></i> </div>
                <div class="side-menu__title"> Manage Students </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.provider.student.requests') }}" class="side-menu @if(\Route::current()->getName() == 'portal.provider.student.requests') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="user-check"></i> </div>
                <div class="side-menu__title"> Registration Requests </div>
            </a>
        </li>
        <li>
            <a href="./all-scans.php" class="side-menu <?php if(isset($page) && $page == 'all-scans'){ echo 'side-menu--active'; } ?>">
                <div class="side-menu__icon"> <i data-feather="search"></i> </div>
                <div class="side-menu__title"> My Scans </div>
            </a>
        </li>
        <li>
            <a href="./search-repository.php" class="side-menu <?php if(isset($page) && $page == 'search-repo'){ echo 'side-menu--active'; } ?>">
                <div class="side-menu__icon"> <i data-feather="zoom-in"></i> </div>
                <div class="side-menu__title"> Search Repository </div>
            </a>
        </li>
        <li>
            <a href="javascript:;" class="side-menu <?php if(isset($page) && $page == 'repo'){ echo 'side-menu--active'; } ?>">
                <div class="side-menu__icon"> <i data-feather="database"></i> </div>
                <div class="side-menu__title">
                    Repository
                    <div class="side-menu__sub-icon"> <i data-feather="chevron-down"></i> </div>
                </div>
            </a>
            <ul class="">
                <li>
                    <a href="./repository.php" class="side-menu">
                        <div class="side-menu__icon"> <i data-feather="file-text"></i> </div>
                        <div class="side-menu__title"> My Documents </div>
                    </a>
                </li>
                <li>
                    <a href="./categories.php" class="side-menu">
                        <div class="side-menu__icon"> <i data-feather="list"></i> </div>
                        <div class="side-menu__title"> Categories </div>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:;" class="side-menu @route('portal.provider.account*') side-menu--active @endroute">
                <div class="side-menu__icon"> <i data-feather="settings"></i> </div>
                <div class="side-menu__title">
                    Account
                    <div class="side-menu__sub-icon"> <i data-feather="chevron-down"></i> </div>
                </div>
            </a>
            <ul class="">
                <li>
                    <a href="{{ route('portal.provider.account.password.change') }}" class="side-menu">
                        <div class="side-menu__icon"> <i data-feather="lock"></i> </div>
                        <div class="side-menu__title"> Change Password </div>
                    </a>
                </li>
                <li>
                    <a href="./profile.php" class="side-menu">
                        <div class="side-menu__icon"> <i data-feather="user"></i> </div>
                        <div class="side-menu__title"> Update Profile </div>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</nav>
<!-- END: Side Menu -->

resources/views/portal/provider/inc/student-delete-modal.blade.php
<!-- BEGIN: Delete Confirmation Modal -->
<div id="delete-confirmation-modal{{ $student->user_id }}" class="modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body p-0">
                <div class="p-5 text-center">
                    <i data-feather="x-circle" class="w-16 h-16 text-theme-6 mx-auto mt-3"></i>
                    <div class="text-3xl mt-5">Are you sure?</div>
                    <div class="text-gray-600 mt-2">
                        Do you really want to delete {{ $student->fname.' '.$student->lname }} records?
                        <br>
                        This process cannot be undone.
                    </div>
                </div>
                <div class="px-5 pb-8 text-center">
                    <button type="button" data-dismiss="modal" class="btn btn-outline-secondary w-24 mr-1">Cancel</button>
                    <a href="{{ route('portal.provider.lecturer.delete', $student->user_id) }}" class="btn btn-danger w-24">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END: Delete Confirmation Modal -->

resources/views/portal/provider/inc/styles.blade.php
<link href="{{ asset('dist/images/icon.png') }}" rel="shortcut icon">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="author" content="{{ $appCr }}">
<!-- BEGIN: CSS Assets-->
{{--<link rel="stylesheet" href="{{ asset('css/bulma.css') }}" />--}}
<link rel="stylesheet" href="{{ asset('css/boxicons.css') }}" />
<link rel="stylesheet" href="{{ asset('dist/css/app.css') }}" />