routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.index');
});

Auth::routes();

// Admin Routes
Route::middleware('auth')->name('portal.')->prefix('portal')->group(function () {
    Route::get('/', 'PortalController@index')->name('home');
    Route::prefix('admin')->name('admin.')->middleware('admin')->group( function(){
        Route::get('/', 'AdminController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('provider')->name('provider.')->group( function() {
            Route::get('/', 'AdminController@providers')->name('home');
            Route::get('create', 'AdminController@create')->name('create');
            Route::get('edit/{provider}', 'AdminController@edit')->name('edit');
            Route::post('store', 'AdminController@store')->name('store');
            Route::patch('update/{provider}', 'AdminController@update')->name('update');
            Route::get('delete/{provider}', 'AdminController@destroy')->name('delete');
        });
    });

    // Provider Routes
    Route::prefix('provider')->name('provider.')->middleware('provider')->group( function(){
        Route::get('/', 'ProviderController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('lecturer')->name('lecturer.')->group( function() {
            Route::get('/', 'ProviderController@lecturers')->name('home');
            Route::get('create', 'ProviderController@create')->name('create');
            Route::get('edit/{lecturer}', 'ProviderController@edit')->name('edit');
            Route::post('store', 'ProviderController@store')->name('store');
            Route::patch('update/{lecturer}', 'ProviderController@update')->name('update');
            Route::get('delete/{lecturer}', 'ProviderController@destroy')->name('delete');

            Route::get('activate/{lecturer}', 'ProviderController@activate')->name('activate');
            Route::get('deactivate/{lecturer}', 'ProviderController@deactivate')->name('deactivate');
        });
        Route::prefix('student')->name('student.')->group( function() {
            Route::get('/', 'ProviderController@students')->name('home');
            Route::get('edit/{student}', 'ProviderController@editStudent')->name('edit');
            Route::get('requests', 'ProviderController@studentRequests')->name('requests');
            Route::patch('update/{student}', 'ProviderController@updateStudent')->name('update');
            Route::get('delete/{student}', 'ProviderController@destroyStudent')->name('delete');

            Route::get('activate/{student}', 'ProviderController@activateStudent')->name('activate');
            Route::get('deactivate/{student}', 'ProviderController@deactivateStudent')->name('deactivate');
        });
    });

    // Student Routes
    Route::prefix('student')->name('student.')->middleware('student')->group( function() {
        Route::get('/', 'StudentController@index')->name('home');
        Route::get('/scans', 'StudentController@scans')->name('scans');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::prefix('assignment')->name('assignment.')->group( function() {
            Route::get('/', 'StudentController@assignments')->name('home');
            Route::get('/submission/{assignment}', 'StudentController@submission')->name('submission');
            Route::get('/submit/{assignment}', 'StudentController@submitAssignment')->name('submit');
            Route::post('/scan/{assignment}', 'StudentController@scanAssignment')->name('scan');
        });
    });
    // Instructor Routes
    Route::prefix('instructor')->name('instructor.')->middleware('instructor')->group( function() {
        Route::get('/', 'LecturerController@index')->name('home');
        Route::prefix('account')->name('account.')->group( function() {
            Route::get('/profile', 'UserController@profile')->name('profile');
            Route::prefix('password')->name('password.')->group(function () {
                Route::get('/change', 'UserController@changePassword')->name('change');
                Route::post('/update', 'UserController@updatePassword')->name('update');
            });
        });
        Route::get('/scans', 'LecturerController@scans')->name('scans');
        Route::prefix('assignment')->name('assignment.')->group( function() {
            Route::get('/', 'LecturerController@assignments')->name('home');
            Route::get('/create', 'LecturerController@createAssignment')->name('create');
            Route::get('/edit/{assignment}', 'LecturerController@createAssignment')->name('edit');
            Route::post('/store', 'LecturerController@storeAssignment')->name('store');
            Route::patch('/update/{assignment}', 'LecturerController@updateAssignment')->name('update');
            Route::get('/delete/{assignment}', 'LecturerController@destroyAssignment')->name('delete');
            Route::post('/scan/{assignment}', 'LecturerController@scanAssignment')->name('scan');
        });
        Route::prefix('course')->name('course.')->group( function() {
            Route::get('/', 'LecturerController@courses')->name('home');
            Route::get('/create', 'LecturerController@createCourse')->name('create');
            Route::post('/store', 'LecturerController@storeCourse')->name('store');
            Route::get('/edit/{course}', 'LecturerController@createCourse')->name('edit');
            Route::patch('/update/{course}', 'LecturerController@updateCourse')->name('update');
            Route::get('/delete/{course}', 'LecturerController@destroyCourse')->name('delete');
        });
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Lecturer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Lecturer extends Model
{
    use HasFactory;

    protected $primaryKey = 'user_id';
    protected $table = 'users';

    public function courses()
    {
        return $this->hasMany(Course::class, 'user_id');
    }
}

app/Http/Controllers/LecturerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Assignment;
use App\Models\Course;
use App\Models\Lecturer;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

class LecturerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('portal.lecturer.index');
    }

    public function courses()
    {
        $courses = Course::owner()->paginate(20);
        return view('portal.lecturer.courses', compact('courses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function createCourse(Course $course)
    {
        return view('portal.lecturer.create-course', ['course' => $course]);
    }
    public function storeCourse(Request $request)
    {
        $course = Course::whereCode($request->code)->first();
        if ($course){
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Duplicate Course Code.']);
        }
        $course_create = Course::create([
            'title' => $request->title,
            'code' => $request->code,
            'user_id' => \Auth::id(),
        ]);
        if ($course_create) {
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Course added successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }
    }
    public function updateCourse(Request $request, Course $course)
    {
        $update = $course->update([
            'title' => $request->title,
            'code' => $request->code,
            'user_id' => \Auth::id(),
        ]);
        if ($update) {
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Course updated successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function assignments()
    {
        $assignments = Assignment::whereUser_id(\Auth::id())->paginate(20);
        return view('portal.lecturer.assignments', compact('assignments'));
    }
    public function createAssignment(Assignment $assignment)
    {
        return view('portal.lecturer.create-assignment', compact('assignment'));
    }

    public function storeAssignment(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|string|min:3',
            'course' => 'required|string',
            'start_date' => 'required',
            'end_date' => 'required',
        ]);
        if ($validator->fails()){
            return redirect()->back()->withInput()->withErrors($validator->errors());
        }
        $input = $request->all();
        $input['user_id'] = \Auth::id();
        $input['status'] = '1';
        $input['start_date'] = Carbon::parse($request->start_date)->format('Y-m-d');
        $input['end_date'] = Carbon::parse($request->end_date)->format('Y-m-d');
        $save = Assignment::create($input);
        if ($save){
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Assignment created successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function show(Lecturer $lecturer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function edit(Lecturer $lecturer)
    {
        return view('portal.lecturer.create-assignment', compact('assignment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function updateAssignment(Request $request, Assignment $assignment)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required|string|min:3',
            'course' => 'required|string',
            'start_date' => 'required',
            'end_date' => 'required',
        ]);
        if ($validator->fails()){
            return redirect()->back()->withInput()->withErrors($validator->errors());
        }
        $assignment->title = $request->title;
        $assignment->course = $request->course;
        $assignment->group_by = $request->group_by;
        $assignment->nwords = $request->nwords;
        $assignment->group_by = $request->group_by;
        $assignment->submit_before_end = $request->submit_before_end;
        $assignment->repo_source = $request->repo_source;
        $assignment->show_rel = $request->show_rel;
        $assignment->start_date = Carbon::parse($request->start_date)->format('Y-m-d');
        $assignment->end_date = Carbon::parse($request->end_date)->format('Y-m-d');

        if ($assignment->save()){
            return Redirect::back()->with(['success' => true, 'message' => 'Yay! Assignment updated successfully.']);
        }else{
            return Redirect::back()->with(['error' => true, 'message' => 'Oops!! Something went wrong.']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Lecturer  $lecturer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lecturer $lecturer)
    {
        //
    }
    public function destroyAssignment(Assignment $assignment )
    {
        if ($assignment->delete()) {
            return Redirect::back()->with([ 'message' => "Assignment Deleted Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with([ 'message' => "Oops! Provider not deleted.", 'error' => true]);
        }
    }
    public function destroyCourse(Course $course )
    {
        if ($course->delete()) {
            return Redirect::back()->with([ 'message' => "Course Deleted Successfully!!", 'success' => true]);
        }else {
            return Redirect::back()->with([ 'message' => "Oops! Provider not deleted.", 'error' => true]);
        }
    }
}

resources/views/portal/lecturer/inc/alert.blade.php
<div class="alert @if (Session::has('success')) alert-success @elseif(Session::has('error')) alert-danger @else d-none @endif alert-dismissible show flex items-center mb-2 " role="alert">
    @if(Session::has('success')) <i data-feather="alert-circle" class="w-6 h-6 mr-2"></i> @elseif(Session::has('error'))  <i data-feather="alert-octagon" class="w-6 h-6 mr-2"></i> @endif {{ Session::get('message') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"> <i data-feather="x" class="w-4 h-4"></i> </button>
</div>

resources/views/portal/lecturer/inc/course-delete-modal.blade.php
<!-- BEGIN: Delete Confirmation Modal -->
<div id="delete-confirmation-modal{{ $course->id }}" class="modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body p-0">
                <div class="p-5 text-center">
                    <i data-feather="x-circle" class="w-16 h-16 text-theme-6 mx-auto mt-3"></i>
                    <div class="text-3xl mt-5">Are you sure?</div>
                    <div class="text-gray-600 mt-2">
                        Do you really want to delete {{ $course->title.' ('.$course->code.')' }} records?
                        <br>
                        This process cannot be undone.
                    </div>
                </div>
                <div class="px-5 pb-8 text-center">
                    <button type="button" data-dismiss="modal" class="btn btn-outline-secondary w-24 mr-1">Cancel</button>
                    <a href="{{ route('portal.instructor.course.delete', $course->id) }}" class="btn btn-danger w-24">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END: Delete Confirmation Modal -->

resources/views/portal/lecturer/inc/msidebar.blade.php
<!-- BEGIN: Mobile Menu -->
<div class="mobile-menu md:hidden">
    <div class="mobile-menu-bar">
        <a href="" class="flex mr-auto">
            <img alt="Verify Project" class="w-50" style="width: 30%;" src="{{ asset('dist/images/logo-w.png') }}">
        </a>
        <a href="javascript:;" id="mobile-menu-toggler"> <i data-feather="bar-chart-2" class="w-8 h-8 text-white transform -rotate-90"></i> </a>
    </div>
    <ul class="border-t border-theme-29 py-5 hidden">
        <li>
            <a href="{{ route('portal.instructor.home') }}" class="menu @if(\Route::current()->getName() == 'portal.lecturer.home') menu--active @endif">
                <div class="menu__icon"> <i data-feather="home"></i> </div>
                <div class="menu__title">
                    Dashboard
                </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.instructor.scans') }}" class="menu @if(\Route::current()->getName() == 'portal.lecturer.scans') menu--active @endif">
                <div class="menu__icon"> <i data-feather="search"></i> </div>
                <div class="menu__title"> My Scans </div>
            </a>
        </li>
        <li>
            <a href="./repository.php" class="menu @if(\Route::current()->getName() == 'portal.lecturer.repository.home') menu--active @endif">
                <div class="menu__icon"> <i data-feather="database"></i> </div>
                <div class="menu__title"> Repository </div>
            </a>
        </li>
        <li>
            <a href="javascript:;" class="menu @route('portal.lecturer.course*') menu--active @endroute">
                <div class="menu__icon"> <i data-feather="book"></i> </div>
                <div class="menu__title">
                    Courses
                    <div class="menu__sub-icon"> <i data-feather="chevron-down"></i> </div>
                </div>
            </a>
            <ul class="">
                <li>
                    <a href="{{ route('portal.instructor.course.create') }}" class="menu">
                        <div class="menu__icon"> <i data-feather="file-plus"></i> </div>
                        <div class="menu__title"> Create New Course </div>
                    </a>
                </li>
                <li>
                    <a href="{{ route('portal.instructor.course.home') }}" class="menu">
                        <div class="menu__icon"> <i data-feather="file-text"></i> </div>
                        <div class="menu__title"> All Courses </div>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:;" class="menu  @route('portal.instructor.assignment*') menu--active @endroute">
                <div class="menu__icon"> <i data-feather="check-circle"></i> </div>
                <div class="menu__title">
                    Assignments
                    <div class="menu__sub-icon"> <i data-feather="chevron-down"></i> </div>
                </div>
            </a>
            <ul class="">
                <li>
                    <a href="./instructor-add-assignment.php" class="menu">
                        <div class="menu__icon"> <i data-feather="file-plus"></i> </div>
                        <div class="menu__title"> Create Assignment </div>
                    </a>
                </li>
                <li>
                    <a href="{{ route('portal.instructor.assignment.home') }}" class="menu">
                        <div class="menu__icon"> <i data-feather="file-text"></i> </div>
                        <div class="menu__title"> All Assignemts </div>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:;" class="menu @route('portal.instructor.account*') menu--active @endroute">
                <div class="menu__icon"> <i data-feather="settings"></i> </div>
                <div class="menu__title">
                    Account
                    <div class="menu__sub-icon"> <i data-feather="chevron-down"></i> </div>
                </div>
            </a>
            <ul class="">
                <li>
                    <a href="{{ route('portal.instructor.account.password.change') }}" class="menu">
                        <div class="menu__icon"> <i data-feather="lock"></i> </div>
                        <div class="menu__title"> Change Password </div>
                    </a>
                </li>
                <li>
                    <a href="./profile.php" class="menu">
                        <div class="menu__icon"> <i data-feather="user"></i> </div>
                        <div class="menu__title"> Update Profile </div>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</div>
<!-- END: Mobile Menu -->

resources/views/portal/lecturer/inc/scripts.blade.php
<!-- BEGIN: JS Assets-->
<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=0&libraries=places"></script>
<script src="{{ asset('dist/js/app.js') }}"></script>
<script src="{{ asset('dist/js/jquery-3.6.0.min.js') }}"></script>
<!-- END: JS Assets-->

resources/views/portal/lecturer/inc/sidebar.blade.php
<!-- BEGIN: Side Menu -->
<nav class="side-nav">
    <a href="" class="intro-x flex items-center pl-5 pt-4">
        <img alt="Verify Project" class="w-50" style="width: 70%;" src="{{ asset('dist/images/logo-w.png') }}">
    </a>
    <div class="side-nav__devider my-6"></div>
    <ul>
        <li>
            <a href="{{ route('portal.instructor.home') }}" class="side-menu @if(\Route::current()->getName() == 'portal.instructor.home') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="home"></i> </div>
                <div class="side-menu__title">
                    Dashboard
                </div>
            </a>
        </li>
        <li>
            <a href="{{ route('portal.instructor.scans') }}" class="side-menu @if(\Route::current()->getName() == 'portal.instructor.scans') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="search"></i> </div>
                <div class="side-menu__title"> My Scans </div>
            </a>
        </li>
        <li>
            <a href="./repository.php" class="side-menu @if(\Route::current()->getName() == 'portal.instructor.repository.home') side-menu--active @endif">
                <div class="side-menu__icon"> <i data-feather="database"></i> </div>
                <div class="side-menu__title"> Repository </div>
            </a>
        </li>
        <li>
            <a href="javascript:;" class="side-menu @route('portal.instructor.course*')  side-menu--active @endroute">
                <div class="side-menu__icon"> <i data-feather="book"></i> </div>
                <div class="side-menu__title">
                    Courses
                    <div class="side-menu__sub-icon"> <i data-feather="chevron-down"></i> </div>
                </div>
            </a>
            <ul class="">
                <li>
                    <a href="{{ route('portal.instructor.course.create') }}" class="side-menu">
                        <div class="side-menu__icon"> <i data-feather="file-plus"></i> </div>
                        <div class="side-menu__title"> Create New Course </div>
                    </a>
                </li>
                <li>
                    <a href="{{ route('portal.instructor.course.home') }}" class="side-menu">
                        <div class="side-menu__icon"> <i data-feather="file-text"></i> </div>
                        <div class="side-menu__title"> All Courses </div>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:;" class="side-menu @route('portal.instructor.assignment*') side-menu--active @endroute">
                <div class="side-menu__icon"> <i data-feather="check-circle"></i> </div>
                <div class="side-menu__title">
                    Assignments
                    <div class="side-menu__sub-icon"> <i data-feather="chevron-down"></i> </div>
                </div>
            </a>
            <ul class="">
                <li>
                    <a href="{{ route('portal.instructor.assignment.create') }}" class="side-menu">
                        <div class="side-menu__icon"> <i data-feather="file-plus"></i> </div>
                        <div class="side-menu__title"> Create Assignment </div>
                    </a>
                </li>
                <li>
                    <a href="{{ route('portal.instructor.assignment.home') }}" class="side-menu">
                        <div class="side-menu__icon"> <i data-feather="file-text"></i> </div>
                        <div class="side-menu__title"> All Assignemts </div>
                    </a>
                </li>
            </ul>
        </li>
        <li>
            <a href="javascript:;" class="side-menu @route('portal.instructor.account*') side-menu--active @endroute">
                <div class="side-menu__icon"> <i data-feather="settings"></i> </div>
                <div class="side-menu__title">
                    Account
                    <div class="side-menu__sub-icon"> <i data-feather="chevron-down"></i> </div>
                </div>
            </a>
            <ul class="">
                <li>
                    <a href="{{ route('portal.instructor.account.password.change') }}" class="side-menu">
                        <div class="side-menu__icon"> <i data-feather="lock"></i> </div>
                        <div class="side-menu__title"> Change Password </div>
                    </a>
                </li>
                <li>
                    <a href="./profile.php" class="side-menu">
                        <div class="side-menu__icon"> <i data-feather="user"></i> </div>
                        <div class="side-menu__title"> Update Profile </div>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</nav>
<!-- END: Side Menu -->

resources/views/portal/lecturer/inc/styles.blade.php
<link href="{{ asset('dist/images/icon.png') }}" rel="shortcut icon">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="author" content="{{ $appCr }}">
<!-- BEGIN: CSS Assets-->
{{--<link rel="stylesheet" href="{{ asset('css/bulma.css') }}" />--}}
<link rel="stylesheet" href="{{ asset('css/boxicons.css') }}" />
<link rel="stylesheet" href="{{ asset('dist/css/app.css') }}" />